#!/usr/bin/env bash

# Logical replacement to `git describe --tags`, but not assuming release-changing commits are tagged.

set -euo pipefail

maven_version=$(./mvnw help:evaluate -Dexpression=project.version -q -DforceStdout)

# If the line is not found, the `grep` will exit with non-zero and script will terminate (-o pipefail)
# If there are multiple matches found, the `git rev-list` below will fail to parse arguments and scipt will terminate as well.
version_changing_commit=$(git blame pom.xml | grep "<version>${maven_version}</version>" | awk '{print $1}')

commits_since_version_change=$(git rev-list "${version_changing_commit}..HEAD" | wc -l)

current_commit_short=$(git rev-parse --short HEAD)

printf "%s-u%s-g%s" "${maven_version%-SNAPSHOT}" "${commits_since_version_change}" "${current_commit_short}"
